apiVersion: kubeshark.opstreelabs.in/v1beta1
kind: Kubeshark
metadata:
  labels:
    app.kubernetes.io/name: kubeshark
    app.kubernetes.io/instance: kubeshark-sample
    app.kubernetes.io/part-of: kubeshark-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubeshark-operator
  name: kubeshark-sample
spec:
  hubImage: "kubeshark/hub:latest"
  ingressClassName: "nginx"
  hubReplicas: 1
  workerImage: "kubeshark/worker:latest"
  ingressHost: "kubeshark.opstreelabs.in"
  hubConfigMapData:
    REACT_APP_DEFAULT_FILTER: "ALL"  # Set the default filter or any other required value
