//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubeshark) DeepCopyInto(out *Kubeshark) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubeshark.
func (in *Kubeshark) DeepCopy() *Kubeshark {
	if in == nil {
		return nil
	}
	out := new(Kubeshark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kubeshark) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubesharkList) DeepCopyInto(out *KubesharkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kubeshark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubesharkList.
func (in *KubesharkList) DeepCopy() *KubesharkList {
	if in == nil {
		return nil
	}
	out := new(KubesharkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubesharkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubesharkSpec) DeepCopyInto(out *KubesharkSpec) {
	*out = *in
	if in.HubReplicas != nil {
		in, out := &in.HubReplicas, &out.HubReplicas
		*out = new(int32)
		**out = **in
	}
	if in.HubConfigMapData != nil {
		in, out := &in.HubConfigMapData, &out.HubConfigMapData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClusterRoleRules != nil {
		in, out := &in.ClusterRoleRules, &out.ClusterRoleRules
		*out = make([]v1.PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HubLabels != nil {
		in, out := &in.HubLabels, &out.HubLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HubContainerPorts != nil {
		in, out := &in.HubContainerPorts, &out.HubContainerPorts
		*out = make([]corev1.ContainerPort, len(*in))
		copy(*out, *in)
	}
	if in.WorkerLabels != nil {
		in, out := &in.WorkerLabels, &out.WorkerLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.SecretKubeshark = in.SecretKubeshark
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubesharkSpec.
func (in *KubesharkSpec) DeepCopy() *KubesharkSpec {
	if in == nil {
		return nil
	}
	out := new(KubesharkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubesharkStatus) DeepCopyInto(out *KubesharkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubesharkStatus.
func (in *KubesharkStatus) DeepCopy() *KubesharkStatus {
	if in == nil {
		return nil
	}
	out := new(KubesharkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKubesharkSpec) DeepCopyInto(out *SecretKubesharkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKubesharkSpec.
func (in *SecretKubesharkSpec) DeepCopy() *SecretKubesharkSpec {
	if in == nil {
		return nil
	}
	out := new(SecretKubesharkSpec)
	in.DeepCopyInto(out)
	return out
}
